export const PLANET_CODES = {
    'Ag': 'Agricultural',
    'As': 'Asteroid',
    'Ba': 'Barren',
    'De': 'Desert',
    'Fl': 'Fluid Oceans',
    'Ga': 'Garden',
    'Hi': 'High Population',
    'Ht': 'High Tech',
    'Ic': 'Ice-Capped',
    'In': 'Industrial',
    'Lo': 'Low Population',
    'Lt': 'Low Tech',
    'Na': 'Non-Agricultural',
    'Ni': 'Non-Industrial',
    'Po': 'Poor',
    'Ri': 'Rich',
    'Va': 'Vacuum',
    'Wa': 'Waterworld',
  
    'Gz': 'Green Zone',
    'Az': 'Amber Zone',
    'Rz': 'Red Zone',

    'all': '',
};

// U means unsuitable for this planet type
export const PLANET_CODES_CONDITIONS = {
    'Ag': 'U U 4-9 4-8 5-7 U U U U',
    'As': 'U 0 0 0 U U U U U',
    'Ba': 'U U U U 0 0 0 U U',
    'De': 'U U 2-9 0 U U U U U',
    'Fl': 'U U A+ 1+ U U U U U',
    'Ga': 'U 6-8 5,6,8 5-7 U U U U U',
    'Hi': 'U U U U 9+ U U U U',
    'Ht': 'U U U U U U U C+ U',
    'Ic': 'U U 0-1 1+ U U U U U',
    'In': 'U U 0-2,4,7,9-C U 9+ U U U U',
    'Lo': 'U U U U 1-3 U U U U',
    'Lt': 'U U U U 1+ U U 5- U',
    'Na': 'U U 0-3 0-3 6+ U U U U',
    'Ni': 'U U U U 4-6 U U U U',
    'Po': 'U U 2-5 0-3 U U U U U',
    'Ri': 'U U 6,8 U 6-8 4-9 U U U',
    'Va': 'U U 0 U U U U U U',
    'Wa': 'U U 3-9,D+ A+ U U U U U',
};
  
export const PDM = [
    {'In': 2, 'Ht': 3, 'Ri': 1},
    {'Na': 2, 'In': 5},
    {'Na': 2, 'In': 5},
    {'Ag': 3, 'Ga': 2},
    {'Ag': 3, 'Wa': 2, 'Ga': 1, 'As': -4},
    {'As': 4},
  
    {'In': 2, 'Ht': 3},
    {'In': 2, 'Ht': 1},
    {'In': 1},
    {'Ht': 2},
    {'Ht': 2},
    {'Ag': 1, 'Wa': 2},
  
    {'As': 2, 'De': 1, 'Ic': 1},
    {'Ht': 1},
    {'Ag': 2},
    {'Ag': 2, 'Wa': 1},
    {'Hi': 1},
    {'Ht': 2},
  
    {'De': 2},
    {'As': 2, 'Hi': 1},
    {'In': 1},
    {'As': 3, 'De': 1, 'Ic': 2},
    {'As': 2, 'Lo': 2},
    {'In': 1},
  
    {'De': 2},
    {'Ag': 7},
    {'As': 4},
    {'Ag': 2, 'Wa': 1},
    {'Ag': 6},
    {'In': 2, 'Ht': 1},
  
    {'Wa': 2},
    {'Ht': 1},
    {'As': 1, 'De': 1, 'Ga': 1, 'Wa': 1},
    {'Ag': 2, 'Wa': 1},
    {'Ht': 2},
    {},
];
  
export const SDM = [
    {'Ni': 2, 'Lt': 1, 'Po': 1},
    {'Ni': 3, 'Ag': 2},
    {'Ni': 3, 'Hi': 2},
    {'In': 2, 'Po': 2},
    {'As': 1, 'Fl': 1, 'Ic': 1, 'Hi': 1},
    {'In': 3, 'Ni': 1},
  
    {'Ni': 1, 'Ri': 2, 'As': 3},
    {'As': 2, 'Ni': 1},
    {'Hi': 1, 'Ri': 2},
    {'Po': 1, 'Az': 2, 'Rz': 4},
    {'As': 2, 'Ri': 2},
    {'In': 2},
  
    {'In': 3, 'Ri': 2},
    {'As': 1, 'Ic': 1, 'Ri': 2},
    {'Lo': 3},
    {'Ri': 2, 'Hi': 2},
    {'Ri': 4},
    {'In': 2, 'Po': 1, 'Ri': 1},
  
    {'In': 2, 'Ag': 1, 'Lt': 2},
    {'Ri': 2, 'Lt': 1},
    {'Ri': 2, 'Ni': 1},
    {'Ri': 3, 'In': 2, 'Ht': 1},
    {'In': 3, 'Ht': 1, 'Ni': -2, 'Ag': -3},
    {'Ag': 2, 'Ht': 1},
  
    {'Hi': 2, 'Ri': 3, 'Po': 3},
    {'Hi': 3, 'Na': 2},
    {'In': 3, 'Ni': 1},
    {'In': 2, 'Ht': 1},
    {'Ri': 2, 'In': 1},
    {'Ni': 2, 'Hi': 1},
  
    {'In': 6},
    {'As': 4, 'Ic': 4, 'Ri': 8, 'Az': 6, 'Rz': 6},
    {'Ri': 6, 'Hi': 6},
    {'Ri': 6, 'Hi': 4},
    {'Po': 6, 'Az': 8, 'Rz': 10},
    {},
];

export const ILLEGAL_GOODS_ID = [
    61, 62, 63, 64, 65
];
  
export const ALL_GOODS_WITHOUT_DM = [
    {'id': 11, 'type': 'Common Electronics', 'availability': 'all', 'tons': '2D*10', 'bp': 'Cr20000'},
    {'id': 12, 'type': 'Common Industrial Goods', 'availability': 'all', 'tons': '2D*10', 'bp': 'Cr10000'},
    {'id': 13, 'type': 'Common Manufactured Goods', 'availability': 'all', 'tons': '2D*10', 'bp': 'Cr20000'},
    {'id': 14, 'type': 'Common Raw Materials', 'availability': 'all', 'tons': '2D*20', 'bp': 'Cr5000'},
    {'id': 15, 'type': 'Common Consumables', 'availability': 'all', 'tons': '2D*20', 'bp': 'Cr500'},
    {'id': 16, 'type': 'Common Ore', 'availability': 'all', 'tons': '2D*20', 'bp': 'Cr1000'},
  
    {'id': 21, 'type': 'Advanced Electronics', 'availability': 'In Ht', 'tons': '1D*5', 'bp': 'Cr100000'},
    {'id': 22, 'type': 'Advanced Machine Parts', 'availability': 'In Ht', 'tons': '1D*5', 'bp': 'Cr75000'},
    {'id': 23, 'type': 'Advanced Manufactured Goods', 'availability': 'In Ht', 'tons': '1D*5', 'bp': 'Cr100000'},
    {'id': 24, 'type': 'Advanced Weapons', 'availability': 'In Ht', 'tons': '1D*5', 'bp': 'Cr150000'},
    {'id': 25, 'type': 'Advanced Vehicles', 'availability': 'In Ht', 'tons': '1D*5', 'bp': 'Cr180000'},
    {'id': 26, 'type': 'Biochemicals', 'availability': 'Ag Wa', 'tons': '1D*5', 'bp': 'Cr50000'},
  
    {'id': 31, 'type': 'Crystals & Gems', 'availability': 'As De Ic', 'tons': '1D*5', 'bp': 'Cr20000'},
    {'id': 32, 'type': 'Cybernetics', 'availability': 'Ht', 'tons': '1D', 'bp': 'Cr250000'},
    {'id': 33, 'type': 'Live Animals', 'availability': 'Ag Ga', 'tons': '1D*10', 'bp': 'Cr10000'},
    {'id': 34, 'type': 'Luxury Consumables', 'availability': 'Ag Ga Wa', 'tons': '1D*10', 'bp': 'Cr20000'},
    {'id': 35, 'type': 'Luxury Goods', 'availability': 'Hi', 'tons': '1D', 'bp': 'Cr200000'},
    {'id': 36, 'type': 'Medical Supplies', 'availability': 'Ht Hi', 'tons': '1D*5', 'bp': 'Cr50000'},
  
    {'id': 41, 'type': 'Petrochemicals', 'availability': 'De Fl Ic Wa', 'tons': '1D*10', 'bp': 'Cr10000'},
    {'id': 42, 'type': 'Pharmaceuticals', 'availability': 'As De Hi Wa', 'tons': '1D', 'bp': 'Cr100000'},
    {'id': 43, 'type': 'Polymers', 'availability': 'In', 'tons': '1D*10', 'bp': 'Cr7000'},
    {'id': 44, 'type': 'Precious Metals', 'availability': 'As De Ic Fl', 'tons': '1D', 'bp': 'Cr50000'},
    {'id': 45, 'type': 'Radioactives', 'availability': 'As De Lo', 'tons': '1D', 'bp': 'MCr1'},
    {'id': 46, 'type': 'Robots', 'availability': 'In', 'tons': '1D*5', 'bp': 'Cr400000'},
  
    {'id': 51, 'type': 'Spices', 'availability': 'Ga De Wa', 'tons': '1D*10', 'bp': 'Cr6000'},
    {'id': 52, 'type': 'Textiles', 'availability': 'Ag Ni', 'tons': '1D*20', 'bp': 'Cr3000'},
    {'id': 53, 'type': 'Uncommon Ore', 'availability': 'As Ic', 'tons': '1D*20', 'bp': 'Cr5000'},
    {'id': 54, 'type': 'Uncommon Raw Materials', 'availability': 'Ag De Wa', 'tons': '1D*10', 'bp': 'Cr20000'},
    {'id': 55, 'type': 'Wood', 'availability': 'Ag Ga', 'tons': '1D*20', 'bp': 'Cr1000'},
    {'id': 56, 'type': 'Vehicles', 'availability': 'In Ht', 'tons': '1D*10', 'bp': 'Cr15000'},
  
    {'id': 61, 'type': 'Illegal Biochemicals', 'availability': 'Ag Wa', 'tons': '1D*5', 'bp': 'Cr50000'},
    {'id': 62, 'type': 'Cybernetics, Illegal', 'availability': 'Ht', 'tons': '1D', 'bp': 'Cr250000'},
    {'id': 63, 'type': 'Drugs, Illegal', 'availability': 'As De Hi Wa', 'tons': '1D', 'bp': 'Cr100000'},
    {'id': 64, 'type': 'Luxuries, Illegal', 'availability': 'Ag Ga Wa', 'tons': '1D', 'bp': 'Cr50000'},
    {'id': 65, 'type': 'Weapons, Illegal', 'availability': 'In Ht', 'tons': '1D*5', 'bp': 'Cr150000'},
    {'id': 66, 'type': 'Exotics', 'availability': '-', 'tons': '-', 'bp': '-'},
];

export const PLANETS_SIZE = [
    'Diameter: < 1000km, gravity: negligible',
    'Diameter: 1600km, gravity: 0.05',
    'Diameter: 3200km, gravity: 0.15',
    'Diameter: 4800km, gravity: 0.25',
    'Diameter: 6400km, gravity: 0.35',
    'Diameter: 8000km, gravity: 0.45',
    'Diameter: 9600km, gravity: 0.7',
    'Diameter: 11200km, gravity: 0.9',
    'Diameter: 12800km, gravity: 1.0',
    'Diameter: 14400km, gravity: 1.25',
    'Diameter: 16000km, gravity: 1.4',
];

export const PLANETS_ATMOSPHERE = [
    'Survival gear required: Vacc Suit',
    'Survival gear required: Vacc Suit',
    'Survival gear required: Respirator, Filter',
    'Survival gear required: Respirator',
    'Survival gear required: Filter',
    'Survival gear required: None',
    'Survival gear required: None',
    'Survival gear required: Filter',
    'Survival gear required: None',
    'Survival gear required: Filter',
    'Survival gear required: Air Supply',
    'Survival gear required: Vacc Suit',
    'Survival gear required: Vacc Suit',
    'Survival gear required: None',
    'Survival gear required: None',
    'Survival gear required: Varies',
];

export const PLANETS_HYDROGRAPHICS = [
    'Hydrographics: Desert world',
    'Hydrographics: Dry world',
    'Hydrographics: A few small seas',
    'Hydrographics: Small seas and oceans', 
    'Hydrographics: Wet world',
    'Hydrographics: A large ocean',
    'Hydrographics: Large oceans',
    'Hydrographics: Earth-like world',
    'Hydrographics: Only a few islands and archipelagos',
    'Hydrographics: Almost entirely water',
    'Hydrographics: Waterworld',
];

export const PLANETS_POPULATION = [
    'Population: 0',
    'Population: >1',
    'Population: >100',
    'Population: >1.000',
    'Population: >10.000',
    'Population: >100.000',
    'Population: >1.000.000',
    'Population: >10.000.000',
    'Population: >100.000.000',
    'Population: >1.000.000.000',
    'Population: >10.000.000.000',
    'Population: >100.000.000.000',
    'Population: >1.000.000.000.000',
];

export const PLANETS_GOVERNMENT = [
    'Government type: None',
    'Government type: Company/Corporation',
    'Government type: Participating Democracy',
    'Government type: Self-Perpetuating Oligarchy',
    'Government type: Representative Democracy',
    'Government type: Feudal Technocracy',
    'Government type: Captive Government',
    'Government type: Balkanisation',
    'Government type: Civil Service Bureaucracy',
    'Government type: Impersonal Bureaucracy',
    'Government type: Charismatic Dictator',
    'Government type: Non-Charismatic Leader',
    'Government type: Charismatic Oligarchy',
    'Government type: Religious Dictatorship',
    'Government type: Religious Autocracy',
    'Government type: Totalitarian Oligarchy',
];

export const PLANETS_LAW = [
    'No restrictions – heavy armour and a handy weapon recommended…',
    'Banned: Poison gas, explosives, undetectable weapons, WMD, Battle dress',
    'Banned: Portable energy and laser weapons, Combat armour',
    'Banned: Military weapons, Flak',
    'Banned: Light assault weapons and submachine guns, Cloth',
    'Banned: Personal concealable weapons, Mesh',
    'Banned: All firearms except shotguns & stunners; carrying weapons discouraged',
    'Banned: Shotguns',
    'Banned: All bladed weapons, stunners, All visible armour',
    'Banned: All weapons, All armour',
    'Banned: All weapons, All armour',
    'Banned: All weapons, All armour',
    'Banned: All weapons, All armour',
    'Banned: All weapons, All armour',
    'Banned: All weapons, All armour',
    'Banned: All weapons, All armour',
];

export const EXPLORED_PLANETS = [
    {'id': 0, 'sectorID': '1932', 'name': 'Horizon', 'planetCode': 'A,5,6,6,9,6,6,E,G', 'flags': 'all Hi Ht Gz'},
    {'id': 1, 'sectorID': '2031', 'name': 'Siberia', 'planetCode': 'C,9,7,2,6,6,1,5,G', 'flags': 'all Lt Ni Gz'},
    {'id': 2, 'sectorID': '1931', 'name': 'Ordos', 'planetCode': 'D,3,4,2,8,7,5,9,G', 'flags': 'all Po Gz'},
    {'id': 3, 'sectorID': '1731', 'name': 'Fincastle', 'planetCode': 'C,1,0,0,5,3,2,C,G', 'flags': 'all Ht Ni Va Gz'},
    {'id': 4, 'sectorID': '1831', 'name': 'Al-Jissa', 'planetCode': 'B,8,3,4,7,4,4,A,G', 'flags': 'all Gz'},
    {'id': 5, 'sectorID': '2131', 'name': 'Aegea', 'planetCode': 'B,7,8,A,5,4,5,9,G', 'flags': 'all Ni Wa Gz'},
    {'id': 6, 'sectorID': '2231', 'name': 'Pacifica', 'planetCode': 'C,8,8,7,7,8,7,5,G', 'flags': 'all Ag Ga Ri Lt Gz'},
    {'id': 7, 'sectorID': '1832', 'name': 'Adriatica', 'planetCode': 'C,5,6,6,8,8,7,6,G', 'flags': 'all Ri Gz'},
    {'id': 8, 'sectorID': '2032', 'name': 'Kyzylkum', 'planetCode': 'E,4,1,0,4,5,6,A,G', 'flags': 'all Ni Gz'},
    {'id': 9, 'sectorID': '2332', 'name': 'Oxus', 'planetCode': 'A,2,2,2,8,9,B,D,G', 'flags': 'all Hi In Po Ht Az'},
    {'id': 10, 'sectorID': '1733', 'name': 'Hyrkania', 'planetCode': 'B,8,7,A,5,8,8,B,G', 'flags': 'all Ni Wa Gz'},
    {'id': 11, 'sectorID': '1833', 'name': 'Tokugawa', 'planetCode': 'D,3,6,3,4,4,4,4,G', 'flags': 'all Ni Lt Gz'},
    {'id': 12, 'sectorID': '2033', 'name': 'Sonora', 'planetCode': 'D,4,2,1,7,8,7,3,R', 'flags': 'all Na Po Lt Rz'},
    {'id': 13, 'sectorID': '2133', 'name': 'Hauk', 'planetCode': 'C,1,0,0,7,9,7,B,G', 'flags': 'all As Na Va Gz'},
    {'id': 14, 'sectorID': '2233', 'name': 'Dagon', 'planetCode': 'B,7,8,A,6,9,8,7,G', 'flags': 'all Ni Ri Wa Gz'},
    {'id': 15, 'sectorID': '2234', 'name': 'Shikatara', 'planetCode': 'C,5,5,4,6,5,6,5,A', 'flags': 'all Ag Ni Lt Az'},
    {'id': 16, 'sectorID': '2335', 'name': 'Euxine', 'planetCode': 'B,7,9,7,8,A,7,8,G', 'flags': 'all Gz'},
    {'id': 17, 'sectorID': '2434', 'name': 'Negev', 'planetCode': 'D,2,3,0,6,A,F,7,A', 'flags': 'all De Na Ni Po Az'},
    {'id': 18, 'sectorID': '2433', 'name': 'Blue Star', 'planetCode': 'B,1,0,0,6,1,7,C,G', 'flags': 'all Na Ni Va Ht Gz'},
    {'id': 19, 'sectorID': '1736', 'name': 'Red', 'planetCode': 'C,1,1,0,4,8,B,A,G', 'flags': 'all Ni Gz'},
    {'id': 20, 'sectorID': '1936', 'name': 'New Earth', 'planetCode': 'B,5,A,A,8,3,1,E,G', 'flags': 'all Fl Ht Gz'},
    {'id': 21, 'sectorID': '2136', 'name': 'Hideria', 'planetCode': 'C,3,7,8,8,1,4,A,A', 'flags': 'all Az'},
    {'id': 22, 'sectorID': '2036', 'name': 'Osiris', 'planetCode': 'C,5,2,2,7,9,7,8,G', 'flags': 'all Na Po Gz'},
    {'id': 23, 'sectorID': '1937', 'name': 'Rosaria', 'planetCode': 'C,7,8,7,7,1,2,6,G', 'flags': 'all Ag Ga Gz'},
    {'id': 24, 'sectorID': '1837', 'name': 'Atacama', 'planetCode': 'D,4,9,0,6,6,9,A,G', 'flags': 'all De Ni Gz'},
    {'id': 25, 'sectorID': '1739', 'name': 'Fieri', 'planetCode': 'C,5,7,7,6,4,3,4,G', 'flags': 'all Ag Ni Lt Gz'},
    {'id': 26, 'sectorID': '1939', 'name': 'Keresia', 'planetCode': 'C,3,5,4,6,A,C,9,G', 'flags': 'all Ag Ni Gz'},
    {'id': 27, 'sectorID': '2140', 'name': 'Rhine', 'planetCode': 'D,A,8,6,2,5,1,7,G', 'flags': 'all Lo Gz'},
    {'id': 28, 'sectorID': '2238', 'name': 'La Isabela', 'planetCode': 'A,8,6,6,8,9,8,C,G', 'flags': 'all Ga Ri Ht Gz'},
    {'id': 29, 'sectorID': '2339', 'name': 'Wang Tong', 'planetCode': 'C,4,6,6,5,4,2,6,G', 'flags': 'all Ag Ni Gz'},
    {'id': 30, 'sectorID': '2438', 'name': 'New Jamaica', 'planetCode': 'D,5,3,5,0,0,0,0,A', 'flags': 'all Ba Ni Az'},
    {'id': 31, 'sectorID': '2437', 'name': 'Rlyeh', 'planetCode': 'B,8,9,A,7,4,3,A,G', 'flags': 'all Wa Gz'},

    {'id': 32, 'sectorID': '2631', 'name': 'Aran', 'planetCode': 'C,7,7,8,8,C,A,8,G', 'flags': 'all Gz' },
    {'id': 33, 'sectorID': '3231', 'name': 'Erume', 'planetCode': 'D,8,5,0,5,5,6,6,G', 'flags': 'all De Ni Po Gz' },
    {'id': 34, 'sectorID': '2732', 'name': 'Mira', 'planetCode': 'A,6,6,5,9,A,6,E,G', 'flags': 'all Ga Ht Ri Gz' },
    {'id': 35, 'sectorID': '2832', 'name': 'Almare', 'planetCode': 'C,5,3,4,6,7,5,A,G', 'flags': 'all Ni Gz' },
    {'id': 36, 'sectorID': '2932', 'name': 'Lusta', 'planetCode': 'B,5,0,0,6,4,4,9,G', 'flags': 'all Na Ni Va Gz' },
    {'id': 37, 'sectorID': '3032', 'name': 'Laikwa', 'planetCode': 'C,A,9,6,7,5,3,8,G', 'flags': 'all Ag Gz' },
    {'id': 38, 'sectorID': '3132', 'name': 'Helke', 'planetCode': 'B,2,0,2,5,4,6,B,G', 'flags': 'all Ic Ni Va Gz' },
    {'id': 39, 'sectorID': '3232', 'name': 'Parka', 'planetCode': 'B,2,2,0,5,5,3,B,G', 'flags': 'all De Ni Po Gz' },
    {'id': 40, 'sectorID': '2533', 'name': 'Zakat', 'planetCode': 'D,9,A,4,3,4,1,7,A', 'flags': 'all Fl Lo Az' },
    {'id': 41, 'sectorID': '3133', 'name': 'Rena', 'planetCode': 'C,5,6,6,7,5,7,6,G', 'flags': 'all Ag Ri Gz' },
    {'id': 42, 'sectorID': '2934', 'name': 'Tirin', 'planetCode': 'E,3,3,2,6,2,3,6,G', 'flags': 'all Na Po Gz' },
    {'id': 43, 'sectorID': '3134', 'name': 'Inga', 'planetCode': 'C,9,A,5,8,5,4,5,G', 'flags': 'all Fl Lt Gz' },
    {'id': 44, 'sectorID': '2635', 'name': 'Pereles', 'planetCode': 'E,6,5,7,2,0,0,4,G', 'flags': 'all Ga Lo Lt Gz' },
    {'id': 45, 'sectorID': '3136', 'name': 'Instuv', 'planetCode': 'E,9,8,8,2,0,0,4,G', 'flags': 'all Lo Lt Gz' },
    {'id': 46, 'sectorID': '2537', 'name': 'Zolotoy', 'planetCode': 'C,5,6,1,5,A,A,6,A', 'flags': 'all Az' },
    {'id': 47, 'sectorID': '2737', 'name': 'Eden', 'planetCode': 'C,5,5,7,5,6,3,9,G', 'flags': 'all Ag Gz' },
    {'id': 48, 'sectorID': '2837', 'name': 'Al-Karrak', 'planetCode': 'B,5,7,2,5,3,6,B,G', 'flags': 'all Ni Gz' },
    {'id': 49, 'sectorID': '2738', 'name': 'Delgovichia', 'planetCode': 'D,4,7,5,4,3,4,5,A', 'flags': 'all Lt Ni Az' },
    {'id': 50, 'sectorID': '2838', 'name': 'Salaam', 'planetCode': 'C,6,4,7,8,C,C,6,G', 'flags': 'all Gz' },
    {'id': 51, 'sectorID': '3038', 'name': 'Steppe', 'planetCode': 'C,7,6,5,8,8,8,4,G', 'flags': 'all Ga Lt Ri Gz' },
    {'id': 52, 'sectorID': '2639', 'name': 'Al-Matabbah', 'planetCode': 'X,6,7,6,4,3,2,3,A', 'flags': 'all Lt Ni Az' },
    {'id': 53, 'sectorID': '3039', 'name': 'Acrisia', 'planetCode': 'A,5,4,4,9,2,2,B,G', 'flags': 'all Hi In Gz' },
];